"""
Project Euler Problem 12
========================

The sequence of triangle numbers is generated by adding the natural
numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 =
28. The first ten terms would be:

                 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

   1: 1
   3: 1,3
   6: 1,2,3,6
  10: 1,2,5,10
  15: 1,3,5,15
  21: 1,3,7,21
  28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five
divisors.

What is the value of the first triangle number to have over five hundred
divisors?
"""

import math


def triangle_over_500_divisors():
    for t in triangle_numbers():
        if len(list(factors(t))) > 500:
            return t


def factors(n):
    # Factors come in couple. Given n = 100: 1, 100; 2, 50; 4 25; ...
    for i in range(1, int(math.sqrt(n))+1):
        if n % i == 0:
            yield i
            m = n / i
            if m != i:
                yield m


def triangle_numbers():
    tn = 0
    i = 1
    while True:
        tn += i
        yield tn
        i += 1


if __name__ == "__main__":
    print(triangle_over_500_divisors())

