"""
Project Euler Problem 2
=======================

Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will be:

                  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not
exceed four million.
"""


def fibo():
    a, b = 1, 2
    yield a
    yield b
    while True:
        a, b = b, a+b
        yield b


def problem2():
    s = 0
    for f in fibo():
        if f >= 4 * 10**6:
            break
        if f % 2 == 0:
            s += f
    return s


if __name__ == "__main__":
    print(problem2())
